version: '3.7'
services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 23306:3306
    volumes:
      - ./db:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    container_name: bienesRaices
    ports:
      - 3000:3000
    environment:
      - PORT=${PORT}
    links:
      - db

